sudo: required
language: java
jdk: oraclejdk8
 
services:
  - docker 
 
env:
  global:
  - secure: "nl+0RdBglOzfmTAL0Cydb6PPrNWDxfFWClv8gMiEWzhsfoalL/J+Gglj3lUHU18DRDiG09SyIyh+G6eNmbAfnEcy/t1abV+Um6fMa/Z/4N8135nQcu1GtaXPMUmOFUsa3rP+vvsc4e7p/mqnlsHZuU0a8sqs2+OQ9GfoV3YaI17l56+oZG4W68X+WE4XHuo7g3GE2xNFKx1Bwg++Jb2TEa9cloi9qLf7vr8tsmKsU0Da2Hed4sdmJGCxkNklOaMqmZJv2ryxMPtV+l/CvJDdQZPXQMXlSGAzO2oyMxgyFJ2b4oqmK8IXwZYKjiSMlSGDBi4XLWCHWc0Odu4WzvyKg9LTILq8VMRJbb8iWtDCARBVj+UxOQBje6/qjYVo6cc8oyKn8ZfFDP4pPFNG9mVArvEYXfTG+7nGGDJ5ZwLSoRXN6IyBKuxz6WCkba8+kBroqDg/EzTxpb6j4mWrCs35ZI5H5qC6WysHcwEsg2UKcVIblsXxbku///admHn/Lp1AJY8Tl7BwS4T3fnoCVXwsg+mxoGliG6huRGXBbODSFYLYc/23ZA4Ve+AjVB0GI5gzMl2AbYSnEGbHruMpkrR3J0QDf8EfCA5aO5VvfFKXwI5qARUN+HjI38jeYyGwXWuZYPvCFxHpUt5ZKj9rwENeU7sVOPVa/RDvtQ6/FwdqX4w="
  - secure: "0CO6maJRE+Uy/vy0hQxzVitXbRKGZnignyUFnvROSNzABER28FcoeeT1PWXnIEMb0q2P39b2O0TGOzZyCKN02ezs72iNBt46o8qW7SSMivNivDlW1HoWmr06fkVkFd/a/P1268H1mD4T/zF7Vq1M0Rk3YRM8v903dXpXpH399yj9lXNTPnmaDKeqRxzBe4T9HMBpBcRDaeptW5Pv4Rn+EgAuWQxcJv6oOJUGnuoJbIKoYyn9HBQB32KgFcCv9m78LF5ZApeuzydMM0a2JJbpNYWL4OHq9PcBmA3OQHBSeq5uSBDTChh1bfs/MdYrNQRqXObkKGgQPj9x30EOlyBnmYTAwH5XF+cZyJVg7fIH4VkW6L/ApkYt+waJK00uZpgqDPVPF2ydAtyaUsMduxgYZcBNU8dEGvO88Jccs6XDPIpdIAP4yl4E9iUZ1UeAXJv7tENP8P5EBUonqUVwJXozzJWDCCZXpabiVw7OnDQ/LQVE/5r3DvMldqe28cxq5iC3cSHEi3nZmk+MkBNCkAkDnaGqckGocV7vYOVBSO+PJT5amOPzUtDV6c2VEvS2ExgN1x8Ekwtc6R3z8LffPdrhijSMA/rvP40Q/G491xZcPo2O8Zh+hJ9IaEUEG+psi9AMeDCnN2KV1zi6qHfpFqbwNj66J27NBj27ghXc1JCs3Eg="
  - secure: "zdnT7CaWPrjW0/ajSR7d2WwA6RFf0N3j3uw0tx+kvFIe/eNu2iUOMzLvEFkQjjZjuN6Fl0P0qIobgCbGCLkaqtU2qRDOqW48k+HAOW/jMwYT87svTBZR6OmBtgJMADpiqp07u9Z2pm9roLdiGva7CEhOmZIsx8dG6RqNxYOcWlgIAmlY2b+kOjVkz2ZuIxGLoJWKjzXuci9xy5sLYj7dG+OontWV0VuPnp8kvjxRJoaZmpLYhT/CvDoMCxJzqrjupe9968Mu8LEIxV5KN/GRxSbCBjHU7oY6ddIQtNrevskwFwr4TDzBO8wE5itWweOpNeY3+XlA1jdDaADh2KrKFCGSSwo3lT5S23v4rqeBQJ+CimmUAsVTtrR8lUS2sLhJf/lhNQz7Yfit7nMK/+i2gOb9qThtcdh7/gfFUALxL3AFWEcUq43ECByhwMIV2WPG3ao6U6kUUEH0XeOTuKyk9t5jZqoiNfsb5F2PXxXcbNCO7aGL7MhWsDd7+o4fOpcMtcmjlxOKONDpLgfzhy0DQSW1OsjkUcc6k+Z6FlqRu9xxlvpaNjg0shtUqsZBiTlvQPAJE4HqflO1aQQN7nZkUSiRWvIBS2lOCfXCZfrX5R+YChXLB0cRnK1PuHkb8cesDghdkvUDMpLCzFGjfo7ErAHHgZcZ9zfPDABvNpB2dJE="
  - secure: "OWt7bjJtGpV0iDnOVFXtfbDnfpLMJBUqbV4oRuA8ZcRVvRvABtq39Qv4Zl/j1zLutizio3Zwqj3u0R0gNP8FK45AS/g9tlq+zRvVbrg6v+Lq+kua+01WD969PqguzN2f99roFdpfllWsMXaCH9EVqMW55ERyfAKbNNH2I5GqVqSwzHifGyYaQXzbkthid/b6iS5nq+QeZDzIr9SLlUsRMlAaz3q4QR65E3BHj/U/eFrrzxMDw3fwQFJvZg9y+XoQh47gF+YWKqBxfppcVwILeJP8R8Jlq8I9zbsTP6IeVWMfgYfaXh6bykhec+uxKjpzdMQh5OC+6jWTMLcg5IQBkF3DI3szgUFLUAPP5gFrmQJsx9aotm4ZIIttVICfzwJj9eRUGXHoM1rQfK3Wgat+bjXO9gyoSiowI5PETQqMURkl21IL3Sz9ZiyI+Yn8YISBoA6DuJjLhL4DaMRQ8PTbJHREBlWTKR3Z3zxUEn5muD1aDQxhZTQwg4gLh4/3IiMYB8TlhJZ7EQGGllpiaXMsyQGiiLt1OGwtBKJr+6f+Q4HyZMjpyeME1EA67HwmP/o+vlK0tGssPPett308BACsCWy52LcQMFRJvzc2A4nyBgD6Qac8tnkJI/rrI0Hb6DQa+sKGk/cEsU52moYcIxFU4xTJQ3RgaFw0qGoBaUrZZdQ="

addons:
  sonarcloud:
    organization: "blackvagas"
    token:
      secure: $SONAR_TOKEN
 
script:
- ./mvnw clean install -B
- ./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
- export IMAGE_NAME=geehxx/blackvagas-api
- docker build -t $IMAGE_NAME:$COMMIT .
- docker tag $IMAGE_NAME:$COMMIT $IMAGE_NAME:$TAG
- docker push $IMAGE_NAME
 
deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: blackvagasapi 
